services:
    llm:
        build: ./llm
        environment:
            - OLLAMA_HOST="0.0.0.0"
        ports:
            - 11434:11434
        volumes:
            - model:/usr/share/ollama/.ollama/models
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: pokellmon
            POSTGRES_USER: pokellmon
            POSTGRES_PASSWORD: qwe123
        ports:
            - 5432:5432
        volumes:
            - ./database:/var/lib/postgresql

    emulation:
        build: ./emulation
        ports:
            - 9999:9999

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

    pokellmon:
        tty: true
        depends_on:
            db:
                condition: service_started
            emulation:
                condition: service_started
            llm:
                condition: service_started
        volumes:
            - ./pokellmon/.env:/pokellmon/.env
        ports:
            - 12345:6789
        build: ./pokellmon

volumes:
    model:
